# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Axosnet.Tickets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking', '~> 4.0'
  pod 'JSONModel'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'IQKeyboardManager'

  # Pods for Axosnet.Tickets

  target 'Axosnet.TicketsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Axosnet.TicketsUITests' do
    # Pods for testing
  end

end
